// Generated by Cypress Author on 2026-08-25.
// These scenarios isolate search behavior with deterministic API responses; no authenticated UI flow is required.

type SearchImageFixture = {
  nasaImageId: string;
  title: string;
  description: string;
  center: string;
  mission: string | null;
  rover: string | null;
  camera: string | null;
  mediaType: string;
  thumbnailUrl: string;
  imageUrl: string;
  sourceUrl: string;
  dateCreated: string;
  displayDate: string;
  aspectRatio: string;
  urls: {
    thumbnail: string;
    card: string;
    preview: string;
    full: string;
    source: string;
  };
  timeline: {
    year: number;
    month: number;
    day: number;
    date: string;
  };
  keywords: string[];
  relevanceScore: number;
  matchReasons: string[];
};

type SearchResultFixture = {
  images: SearchImageFixture[];
  totalHits: number;
  page: number;
  pageSize: number;
  searchId: string;
  mode: "standard" | "semantic";
  interpretedQuery: string | null;
  appliedFilters: {
    dateFrom: string | null;
    dateTo: string | null;
    rover: string | null;
    camera: string | null;
    mission: string | null;
    inferred: string[];
  };
  degraded: boolean;
  degradationReason: string | null;
  nextCursor: string | null;
  relaxationSuggestions: Array<{
    code: string;
    filter: string;
  }>;
};

const createImage = (id: string, title: string): SearchImageFixture => {
  const assetBaseUrl = `https://images.test/${id}`;

  return {
    nasaImageId: id,
    title,
    description: `${title} fixture description.`,
    center: "JPL",
    mission: "Mars 2020",
    rover: "Perseverance",
    camera: "Mastcam-Z",
    mediaType: "image",
    thumbnailUrl: `${assetBaseUrl}-thumb.jpg`,
    imageUrl: `${assetBaseUrl}.jpg`,
    sourceUrl: `https://images.nasa.gov/details/${id}`,
    dateCreated: "2024-01-02T00:00:00Z",
    displayDate: "2024-01-02",
    aspectRatio: "4/3",
    urls: {
      thumbnail: `${assetBaseUrl}-thumb.jpg`,
      card: `${assetBaseUrl}-card.jpg`,
      preview: `${assetBaseUrl}-preview.jpg`,
      full: `${assetBaseUrl}.jpg`,
      source: `https://images.nasa.gov/details/${id}`
    },
    timeline: {
      year: 2024,
      month: 1,
      day: 2,
      date: "2024-01-02"
    },
    keywords: ["mars", "fixture"],
    relevanceScore: 95,
    matchReasons: ["Matches the requested Mars subject"]
  };
};

const createResult = (overrides: Partial<SearchResultFixture> = {}): SearchResultFixture => ({
  images: [createImage("fixture-1", "Mars fixture")],
  totalHits: 1,
  page: 1,
  pageSize: 24,
  searchId: "search-fixture-1",
  mode: "standard",
  interpretedQuery: null,
  appliedFilters: {
    dateFrom: null,
    dateTo: null,
    rover: null,
    camera: null,
    mission: null,
    inferred: []
  },
  degraded: false,
  degradationReason: null,
  nextCursor: null,
  relaxationSuggestions: [],
  ...overrides
});

const readSearchParams = (): Cypress.Chainable<URLSearchParams> =>
  cy.location("href").then((href) => new URL(href).searchParams);

describe("Search dashboard", () => {
  beforeEach(() => {
    cy.intercept({ method: "POST", pathname: "/api/search/events" }, (request) => {
      expect(request.body).not.to.have.property("query");
      request.reply({ statusCode: 204 });
    }).as("searchTelemetry");
    cy.intercept("GET", "https://images.test/**", {
      statusCode: 200,
      headers: { "content-type": "image/jpeg" },
      body: "fixture-image"
    });
  });

  it("cambia de búsqueda estándar a semántica → usa el endpoint correspondiente", () => {
    cy.intercept({ method: "GET", pathname: "/api/search" }, (request) => {
      expect(request.query.q).to.equal("mars");
      request.reply(createResult({ mode: "standard" }));
    }).as("standardSearch");
    cy.intercept({ method: "GET", pathname: "/api/search/semantic" }, (request) => {
      expect(request.query.q).to.equal("mars");
      expect(request.query.cursor).to.be.undefined;
      request.reply(createResult({
        mode: "semantic",
        interpretedQuery: "mars rover landscape"
      }));
    }).as("semanticSearch");

    cy.visit("/search?q=mars");
    cy.wait("@standardSearch");
    cy.get('[data-cy="semantic-toggle"]')
      .should("have.attr", "aria-pressed", "false")
      .click()
      .should("have.attr", "aria-pressed", "true");
    cy.wait("@semanticSearch");
    cy.get('[data-cy="semantic-interpretation"]')
      .should("be.visible")
      .and("contain.text", "mars rover landscape");
  });

  it("deja la consulta vacía → deshabilita el toggle y no llama al endpoint semántico", () => {
    let semanticRequestCount = 0;

    cy.intercept({ method: "GET", pathname: "/api/search" }, {
      statusCode: 200,
      body: createResult()
    }).as("emptyStandardSearch");
    cy.intercept({ method: "GET", pathname: "/api/search/semantic" }, (request) => {
      semanticRequestCount += 1;
      request.reply(createResult({ mode: "semantic" }));
    });

    cy.visit("/search?semantic=true");
    cy.wait("@emptyStandardSearch");
    cy.get('[data-cy="search-input"]').should("have.value", "");
    cy.get('[data-cy="semantic-toggle"]')
      .should("be.disabled")
      .and("have.attr", "aria-pressed", "false")
      .then(() => {
        expect(semanticRequestCount).to.equal(0);
      });
    cy.get('[data-cy="search-input"]').type("mars");
    cy.get('[data-cy="search-btn"]').click();
    cy.wait("@emptyStandardSearch");
    readSearchParams().then((params) => {
      expect(params.get("q")).to.equal("mars");
      expect(params.has("semantic")).to.equal(false);
      expect(semanticRequestCount).to.equal(0);
    });
  });

  it("elimina una inferencia y cambia la consulta → persiste y luego limpia suppressInferred", () => {
    cy.intercept({ method: "GET", pathname: "/api/search/semantic" }, (request) => {
      if (request.query.q === "saturn rings") {
        request.alias = "changedInferenceQuery";
        expect(request.query.suppressInferred).to.be.undefined;
        request.reply(createResult({
          mode: "semantic",
          interpretedQuery: "saturn rings cassini"
        }));
        return;
      }

      if (request.query.suppressInferred === "camera") {
        request.alias = "removedInferenceQuery";
        expect(request.query.q).to.equal("gale panorama");
        request.reply(createResult({
          mode: "semantic",
          interpretedQuery: "curiosity panorama at gale crater",
          appliedFilters: {
            dateFrom: null,
            dateTo: null,
            rover: "Curiosity",
            camera: null,
            mission: null,
            inferred: ["rover"]
          }
        }));
        return;
      }

      request.alias = "initialInferenceQuery";
      if (request.query.q === "gale panorama") {
        expect(request.query.suppressInferred).to.be.undefined;
        request.reply(createResult({
          mode: "semantic",
          interpretedQuery: "curiosity navcam panorama at gale crater",
          appliedFilters: {
            dateFrom: null,
            dateTo: null,
            rover: "Curiosity",
            camera: "Navcam",
            mission: null,
            inferred: ["rover", "camera"]
          }
        }));
        return;
      }

      request.reply({ statusCode: 400 });
    });

    cy.visit("/search?q=gale%20panorama&semantic=true");
    cy.wait("@initialInferenceQuery");
    cy.get('[data-cy="semantic-interpretation"]')
      .should("contain.text", "curiosity navcam panorama at gale crater");
    cy.get('[data-cy="semantic-inferred-filter"][data-filter="camera"]').click();
    cy.wait("@removedInferenceQuery");
    cy.get('[data-cy="semantic-toggle"]').should("have.attr", "aria-pressed", "true");
    readSearchParams().then((params) => {
      expect(params.get("semantic")).to.equal("true");
      expect(params.get("suppressInferred")).to.equal("camera");
    });

    cy.get('[data-cy="search-input"]').clear().type("saturn rings");
    cy.get('[data-cy="search-btn"]').click();
    cy.wait("@changedInferenceQuery");
    readSearchParams().then((params) => {
      expect(params.get("q")).to.equal("saturn rings");
      expect(params.has("suppressInferred")).to.equal(false);
    });
  });

  it("elimina un filtro explícito → no lo registra como inferencia suprimida", () => {
    cy.intercept({ method: "GET", pathname: "/api/search/semantic" }, (request) => {
      if (request.query.camera === "Navcam") {
        request.alias = "explicitFilterInitial";
        expect(request.query.suppressInferred).to.be.undefined;
        request.reply(createResult({
          mode: "semantic",
          interpretedQuery: "mars terrain photographed with navcam",
          appliedFilters: {
            dateFrom: null,
            dateTo: null,
            rover: null,
            camera: "Navcam",
            mission: null,
            inferred: []
          }
        }));
        return;
      }

      request.alias = "explicitFilterRemoved";
      expect(request.query.q).to.equal("mars terrain");
      expect(request.query.camera).to.be.undefined;
      expect(request.query.suppressInferred).to.be.undefined;
      request.reply(createResult({
        mode: "semantic",
        interpretedQuery: "mars terrain"
      }));
    });

    cy.visit("/search?q=mars%20terrain&semantic=true&camera=Navcam");
    cy.wait("@explicitFilterInitial");
    cy.get('[data-cy="semantic-applied-filter"][data-filter="camera"]').click();
    cy.wait("@explicitFilterRemoved");
    readSearchParams().then((params) => {
      expect(params.has("camera")).to.equal(false);
      expect(params.has("suppressInferred")).to.equal(false);
    });
  });

  it("aplica una sugerencia estricta → elimina solo el filtro indicado", () => {
    cy.intercept({ method: "GET", pathname: "/api/search/semantic" }, (request) => {
      if (request.query.camera === "Navcam") {
        request.alias = "strictSuggestionInitial";
        expect(request.query.mission).to.equal("Mars 2020");
        expect(request.query.camera).to.equal("Navcam");
        request.reply(createResult({
          images: [],
          totalHits: 0,
          mode: "semantic",
          interpretedQuery: "mars navcam terrain",
          appliedFilters: {
            dateFrom: null,
            dateTo: null,
            rover: null,
            camera: "Navcam",
            mission: "Mars 2020",
            inferred: []
          },
          relaxationSuggestions: [{ code: "remove_camera", filter: "camera" }]
        }));
        return;
      }

      request.alias = "strictSuggestionRelaxed";
      expect(request.query.q).to.equal("mars terrain");
      expect(request.query.mission).to.equal("Mars 2020");
      expect(request.query.camera).to.be.undefined;
      expect(request.query.suppressInferred).to.equal("camera");
      request.reply(createResult({
        mode: "semantic",
        interpretedQuery: "mars terrain",
        appliedFilters: {
          dateFrom: null,
          dateTo: null,
          rover: null,
          camera: null,
          mission: "Mars 2020",
          inferred: []
        }
      }));
    });

    cy.visit("/search?q=mars%20terrain&semantic=true&mission=Mars%202020&camera=Navcam");
    cy.wait("@strictSuggestionInitial");
    cy.get('[data-cy="semantic-suggestion"][data-suggestion="remove_camera"]').click();
    cy.wait("@strictSuggestionRelaxed");
    readSearchParams().then((params) => {
      expect(params.get("q")).to.equal("mars terrain");
      expect(params.get("semantic")).to.equal("true");
      expect(params.get("mission")).to.equal("Mars 2020");
      expect(params.has("camera")).to.equal(false);
      expect(params.get("suppressInferred")).to.equal("camera");
    });
  });

  it("retira el rango de fechas sugerido → limpia fechas y preset de la URL", () => {
    cy.intercept({ method: "GET", pathname: "/api/search/semantic" }, (request) => {
      if (request.query.dateFrom !== undefined) {
        request.alias = "dateSuggestionInitial";
        expect(request.query.dateFrom).to.equal("2023-01-01");
        expect(request.query.dateTo).to.equal("2024-01-01");
        request.reply(createResult({
          images: [],
          totalHits: 0,
          mode: "semantic",
          interpretedQuery: "mars during the requested period",
          appliedFilters: {
            dateFrom: "2023-01-01",
            dateTo: "2024-01-01",
            rover: null,
            camera: null,
            mission: null,
            inferred: []
          },
          relaxationSuggestions: [{ code: "remove_date_range", filter: "dateRange" }]
        }));
        return;
      }

      request.alias = "dateSuggestionRelaxed";
      expect(request.query.q).to.equal("mars");
      expect(request.query.dateFrom).to.be.undefined;
      expect(request.query.dateTo).to.be.undefined;
      expect(request.query.suppressInferred).to.equal("dateFrom,dateTo");
      request.reply(createResult({
        mode: "semantic",
        interpretedQuery: "mars without a date restriction"
      }));
    });

    cy.visit("/search?q=mars&semantic=true&datePreset=last-year&dateFrom=2023-01-01&dateTo=2024-01-01");
    cy.wait("@dateSuggestionInitial");
    cy.get('[data-cy="semantic-suggestion"][data-suggestion="remove_date_range"]').click();
    cy.wait("@dateSuggestionRelaxed");
    readSearchParams().then((params) => {
      expect(params.has("datePreset")).to.equal(false);
      expect(params.has("dateFrom")).to.equal(false);
      expect(params.has("dateTo")).to.equal(false);
      expect(params.get("suppressInferred")).to.equal("dateFrom,dateTo");
    });
  });

  it("retira una fecha aplicada → conserva el otro límite y limpia el preset", () => {
    cy.intercept({ method: "GET", pathname: "/api/search/semantic" }, (request) => {
      if (request.query.dateFrom !== undefined) {
        request.alias = "dateBoundaryInitial";
        request.reply(createResult({
          mode: "semantic",
          interpretedQuery: "mars in a bounded period",
          appliedFilters: {
            dateFrom: "2023-01-01",
            dateTo: "2024-01-01",
            rover: null,
            camera: null,
            mission: null,
            inferred: []
          }
        }));
        return;
      }

      request.alias = "dateBoundaryRemoved";
      expect(request.query.dateFrom).to.be.undefined;
      expect(request.query.dateTo).to.equal("2024-01-01");
      request.reply(createResult({
        mode: "semantic",
        interpretedQuery: "mars before the requested date",
        appliedFilters: {
          dateFrom: null,
          dateTo: "2024-01-01",
          rover: null,
          camera: null,
          mission: null,
          inferred: []
        }
      }));
    });

    cy.visit("/search?q=mars&semantic=true&datePreset=last-year&dateFrom=2023-01-01&dateTo=2024-01-01");
    cy.wait("@dateBoundaryInitial");
    cy.get('[data-cy="semantic-applied-filter"][data-filter="dateFrom"]').click();
    cy.wait("@dateBoundaryRemoved");
    readSearchParams().then((params) => {
      expect(params.has("datePreset")).to.equal(false);
      expect(params.has("dateFrom")).to.equal(false);
      expect(params.get("dateTo")).to.equal("2024-01-01");
    });
  });

  it("agota el retry automático y reintenta manualmente → recupera los resultados", () => {
    let allowSuccess = false;
    const eventNames: string[] = [];

    cy.intercept({ method: "POST", pathname: "/api/search/events" }, (request) => {
      eventNames.push(String(request.body.eventName));
      expect(request.body).not.to.have.property("query");
      if (request.body.eventName === "search_error") {
        allowSuccess = true;
        request.alias = "searchErrorTelemetry";
      }
      if (request.body.eventName === "search_completed") {
        request.alias = "searchCompletedTelemetry";
      }
      request.reply({ statusCode: 204 });
    });

    cy.intercept({ method: "GET", pathname: "/api/search/semantic" }, (request) => {
      if (!allowSuccess) {
        request.reply({
          statusCode: 503,
          body: { message: "Semantic provider unavailable" }
        });
        return;
      }

      request.alias = "manualRetrySuccess";
      request.reply(createResult({
        images: [createImage("recovered-1", "Recovered Mars result")],
        mode: "semantic",
        interpretedQuery: "mars recovered search"
      }));
    });

    cy.visit("/search?q=mars&semantic=true");
    cy.wait("@searchErrorTelemetry");
    cy.get('[data-cy="search-retry"]').should("be.visible").click();
    cy.wait("@manualRetrySuccess");
    cy.get('[data-cy="search-retry"]').should("not.exist");
    cy.contains('[data-cy="image-card"]', "Recovered Mars result").should("be.visible");
    cy.wait("@searchCompletedTelemetry");
    cy.then(() => {
      expect(eventNames.filter((eventName) => eventName === "search_submitted")).to.have.length(2);
      expect(eventNames.filter((eventName) => eventName === "search_error")).to.have.length(1);
      expect(eventNames.filter((eventName) => eventName === "search_completed")).to.have.length(1);
    });
  });

  it("navega atrás y recarga → restaura consulta y modo desde la URL", () => {
    cy.intercept({ method: "GET", pathname: "/api/search" }, (request) => {
      request.reply(createResult({
        images: [createImage(`standard-${String(request.query.q ?? "empty")}`, "Standard route result")],
        mode: "standard"
      }));
    }).as("routeStandardSearch");
    cy.intercept({ method: "GET", pathname: "/api/search/semantic" }, (request) => {
      request.reply(createResult({
        images: [createImage(`semantic-${String(request.query.q)}`, "Semantic route result")],
        mode: "semantic",
        interpretedQuery: `${String(request.query.q)} interpreted`
      }));
    }).as("routeSemanticSearch");

    cy.visit("/search?q=mars&mission=Mars%202020");
    cy.wait("@routeStandardSearch");
    cy.get('[data-cy="search-input"]').clear().type("saturn rings");
    cy.get('[data-cy="search-btn"]').click();
    cy.wait("@routeStandardSearch");
    cy.get('[data-cy="semantic-toggle"]').click();
    cy.wait("@routeSemanticSearch");
    readSearchParams().then((params) => {
      expect(params.get("q")).to.equal("saturn rings");
      expect(params.get("semantic")).to.equal("true");
      expect(params.get("mission")).to.equal("Mars 2020");
    });

    cy.go("back");
    cy.get('[data-cy="search-input"]').should("have.value", "saturn rings");
    cy.get('[data-cy="semantic-toggle"]').should("have.attr", "aria-pressed", "false");
    readSearchParams().then((params) => {
      expect(params.get("q")).to.equal("saturn rings");
      expect(params.has("semantic")).to.equal(false);
      expect(params.get("mission")).to.equal("Mars 2020");
    });

    cy.go("forward");
    cy.get('[data-cy="semantic-toggle"]').should("have.attr", "aria-pressed", "true");
    cy.reload();
    cy.wait("@routeSemanticSearch");
    cy.get('[data-cy="search-input"]').should("have.value", "saturn rings");
    cy.get('[data-cy="semantic-interpretation"]').should("contain.text", "saturn rings interpreted");
    readSearchParams().then((params) => {
      expect(params.get("mission")).to.equal("Mars 2020");
      expect(params.get("semantic")).to.equal("true");
    });
  });

  it("abre los filtros en móvil → conserva consulta, modo y filtros de la URL", () => {
    let semanticRequestCount = 0;
    let requestCountBeforeOpeningFilters = 0;

    cy.viewport(390, 844);
    cy.intercept({ method: "GET", pathname: "/api/search/semantic" }, (request) => {
      semanticRequestCount += 1;
      expect(request.query.q).to.equal("mars");
      expect(request.query.mission).to.equal("Mars 2020");
      request.reply(createResult({
        mode: "semantic",
        interpretedQuery: "mars mission images"
      }));
    }).as("mobileSemanticSearch");

    cy.visit("/search?q=mars&semantic=true&mission=Mars%202020");
    cy.wait("@mobileSemanticSearch");
    cy.get('[data-cy="semantic-interpretation"]').should("contain.text", "mars mission images");
    cy.then(() => {
      requestCountBeforeOpeningFilters = semanticRequestCount;
    });
    cy.get('[data-cy="mobile-search"]').should("be.visible").click();
    cy.get('[data-cy="search-input"]').should("be.visible").and("have.value", "mars");
    readSearchParams().then((params) => {
      expect(params.get("q")).to.equal("mars");
      expect(params.get("semantic")).to.equal("true");
      expect(params.get("mission")).to.equal("Mars 2020");
      expect(semanticRequestCount).to.equal(requestCountBeforeOpeningFilters);
    });
  });

  it("carga la página siguiente → envía solo el cursor y no duplica imágenes", () => {
    cy.intercept({ method: "GET", pathname: "/api/search/semantic" }, (request) => {
      if (request.query.cursor === undefined) {
        request.alias = "cursorFirstPage";
        expect(request.query.q).to.equal("mars");
        expect(request.query.cursor).to.be.undefined;
        request.reply(createResult({
          images: [
            createImage("cursor-a", "Cursor result Alpha"),
            createImage("cursor-b", "Cursor result Beta")
          ],
          totalHits: 3,
          pageSize: 2,
          mode: "semantic",
          interpretedQuery: "mars",
          nextCursor: "opaque-cursor-page-2"
        }));
        return;
      }

      request.alias = "cursorSecondPage";
      expect(request.query.cursor).to.equal("opaque-cursor-page-2");
      expect(request.query.q).to.be.undefined;
      expect(request.query.mission).to.be.undefined;
      request.reply(createResult({
        images: [
          createImage("cursor-b", "Cursor result Beta"),
          createImage("cursor-c", "Cursor result Gamma")
        ],
        totalHits: 3,
        page: 2,
        pageSize: 2,
        mode: "semantic",
        interpretedQuery: "mars",
        nextCursor: null
      }));
    });

    cy.visit("/search?q=mars&semantic=true");
    cy.wait("@cursorFirstPage");
    cy.contains('[data-cy="image-card"]', "Cursor result Beta").scrollIntoView();
    cy.wait("@cursorSecondPage");
    cy.get('[data-cy="image-card"]').should("have.length", 3);
    cy.contains('[data-cy="image-card"]', "Cursor result Alpha").should("have.length", 1);
    cy.contains('[data-cy="image-card"]', "Cursor result Beta").should("have.length", 1);
    cy.contains('[data-cy="image-card"]', "Cursor result Gamma").should("have.length", 1);
  });

  it("vence el cursor → reinicia una sola vez la sesión semántica", () => {
    let cursorExpired = false;
    let restartRequestCount = 0;

    cy.intercept({ method: "GET", pathname: "/api/search/semantic" }, (request) => {
      if (request.query.cursor === "expired-cursor") {
        cursorExpired = true;
        request.alias = "expiredCursorPage";
        request.reply({
          statusCode: 410,
          body: { code: "search_session_expired", message: "Search session expired." }
        });
        return;
      }

      if (!cursorExpired) {
        request.alias = "initialCursorSearch";
        request.reply(createResult({
          images: [createImage("expired-a", "Before cursor expiration")],
          totalHits: 2,
          pageSize: 1,
          mode: "semantic",
          interpretedQuery: "mars",
          nextCursor: "expired-cursor"
        }));
        return;
      }

      restartRequestCount += 1;
      request.alias = "restartedCursorSearch";
      expect(request.query.q).to.equal("mars");
      expect(request.query.cursor).to.be.undefined;
      request.reply(createResult({
        images: [createImage("restarted-a", "Restarted semantic result")],
        mode: "semantic",
        interpretedQuery: "mars restarted"
      }));
    });

    cy.visit("/search?q=mars&semantic=true");
    cy.wait("@initialCursorSearch");
    cy.contains('[data-cy="image-card"]', "Before cursor expiration").scrollIntoView();
    cy.wait("@expiredCursorPage");
    cy.wait("@restartedCursorSearch");
    cy.contains('[data-cy="image-card"]', "Restarted semantic result").should("be.visible");
    cy.then(() => {
      expect(restartRequestCount).to.equal(1);
    });
  });

  it("cancela una búsqueda obsoleta → conserva solo el resultado más reciente", () => {
    let marsRequestAborted = false;
    let marsRequestStarted = false;

    cy.intercept({ method: "GET", pathname: "/api/search/semantic" }, (request) => {
      const query = String(request.query.q ?? "");
      request.alias = query === "saturn" ? "saturnSemanticSearch" : "marsSemanticSearch";

      request.reply({
        delay: query === "mars" ? 10000 : 0,
        body: createResult({
          images: [createImage(`result-${query}`, `${query} current result`)],
          mode: "semantic",
          interpretedQuery: query
        })
      });
    });

    cy.visit("/search?q=mars&semantic=true", {
      onBeforeLoad(window) {
        const originalFetch = window.fetch.bind(window);

        window.fetch = (input: RequestInfo | URL, init?: RequestInit): Promise<Response> => {
          const requestUrl = typeof input === "string"
            ? input
            : input instanceof URL
              ? input.toString()
              : input.url;

          if (requestUrl.includes("/api/search/semantic") && requestUrl.includes("q=mars")) {
            const signal = init?.signal ?? (input instanceof Request ? input.signal : undefined);
            marsRequestStarted = true;
            signal?.addEventListener("abort", () => {
              marsRequestAborted = true;
            }, { once: true });
          }

          return originalFetch(input, init);
        };
      }
    });
    cy.wrap(null).should(() => {
      expect(marsRequestStarted).to.equal(true);
    }).then(() => {
      marsRequestAborted = false;
    });
    cy.get('[data-cy="search-input"]').clear().type("saturn");
    cy.get('[data-cy="search-btn"]').click();
    cy.wait("@saturnSemanticSearch");
    cy.contains('[data-cy="image-card"]', "saturn current result").should("be.visible");
    cy.contains('[data-cy="image-card"]', "mars current result").should("not.exist");
    cy.then(() => {
      expect(marsRequestAborted).to.equal(true);
    });
  });

  it("abre un resultado con teclado → registra la interacción sin consulta", () => {
    const eventNames: string[] = [];

    cy.intercept({ method: "POST", pathname: "/api/search/events" }, (request) => {
      eventNames.push(String(request.body.eventName));
      expect(request.body).not.to.have.property("query");
      if (request.body.eventName === "result_opened") {
        request.alias = "resultOpenedTelemetry";
      }
      request.reply({ statusCode: 204 });
    });
    cy.intercept({ method: "GET", pathname: "/api/search/semantic" }, {
      statusCode: 200,
      body: createResult({ mode: "semantic", interpretedQuery: "mars" })
    }).as("keyboardSemanticSearch");

    cy.visit("/search?q=mars&semantic=true");
    cy.wait("@keyboardSemanticSearch");
    cy.get('[data-cy="image-card"]').focus().type("{enter}").should("have.attr", "aria-pressed", "true");
    cy.wait("@resultOpenedTelemetry");
    cy.then(() => {
      expect(eventNames).to.include("result_opened");
    });
  });

  it("cambia a español → envía locale y actualiza los mensajes semánticos", () => {
    cy.intercept({ method: "GET", pathname: "/api/search/semantic" }, (request) => {
      request.alias = request.query.locale === "es" ? "spanishSemanticSearch" : "englishSemanticSearch";
      request.reply(createResult({
        mode: "semantic",
        interpretedQuery: request.query.locale === "es" ? "paisaje de marte" : "mars landscape"
      }));
    });

    cy.visit("/search?q=mars&semantic=true");
    cy.wait("@englishSemanticSearch");
    cy.get('button[aria-label="Language"]').click();
    cy.contains('[role="menuitem"]', "Spanish").click();
    cy.wait("@spanishSemanticSearch").its("request.query.locale").should("equal", "es");
    cy.get('[data-cy="semantic-interpretation"]')
      .should("contain.text", "Interpretamos tu búsqueda como")
      .and("contain.text", "paisaje de marte");
  });
});
